name: sandapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.1
  intl: ^0.18.0
  firebase_core: ^2.24.2
  firebase_auth: any
  google_sign_in: any
  image_picker: ^1.0.8
  permission_handler: ^11.0.1
  video_player: any
  video_thumbnail: any
  firebase_storage: ^11.6.0
  stylish_bottom_bar: ^1.1.0
  font_awesome_flutter: ^10.7.0
  video_trimmer: ^2.1.0
  video_editor: ^3.0.0
  cloud_firestore: ^4.14.0
  # ffmpeg_kit_flutter: ^4.5.1
dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/
    - assets/logos/
    - assets/ice_ball_0.mp4
    - assets/flame_lion_0.mp4
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic  